export { default as MercuryImage } from '../assets/MercuryImages/Mercury.png'
export {default as VenusImage} from '../assets/VenusImages/Venus.png'
export {default as EarthImage} from '../assets/EarthImages/Earth.png'
export {default as MarsImage} from '../assets/MarsImages/Mars.png'
export {default as JupiterImage} from '../assets/JupiterImages/Jupiter.png'
export {default as SaturnImage} from '../assets/SaturnImages/Saturn.png'
export {default as UranusImage} from '../assets/UranusImages/Uranus.png'
export {default as NeptuneImage} from '../assets/NeptuneImages/Neptune.png'
export {default as Sun} from '../assets/Images/sun.png'
export {default as Menu} from '../assets/Images/Group.png'
export {default as Arrow} from '../assets/Images/Path 3.png'
export {default as Mercury} from '../assets/Images/MobileMercury.png'
export {default as Venus} from '../assets/Images/MobileVenus.png'
export {default as Earth} from '../assets/Images/MobileEarth.png'
export {default as Mars} from '../assets/Images/MobileMars.png'
export {default as Jupiter} from '../assets/Images/MobileJupiter.png'
export {default as Saturn} from '../assets/Images/MobileSaturn.png'
export {default as Uranus} from '../assets/Images/MobileUranus.png'
export {default as Neptune} from '../assets/Images/MobileNeptune.png'